name: FCM Notification

on:
  push:

jobs:
  notify:
    name: FCM Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send FCM notification
        uses: ./.github/actions/send_notifications
        with:
          google-credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          firmware-version: 0.98.2
