name: FCM Notification

on:
  push:

jobs:
  notify:
    name: FCM Notification
    runs-on: ubuntu-latest
    steps:
      - uses: 'google-github-actions/auth@v2'
        id: google_auth
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          token_format: "access_token"
      - run: echo ${{ steps.google_auth.outputs.access_token }}
