name: FCM Notification

on:
  push:

jobs:
  notify:
    name: FCM Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send FCM notification
        uses: ./.github/actions/submit_sdk
        with:
          google-credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          firmware-version: 0.98.2
