name: FCM Notification

on:
  push:

jobs:
  notify:
    name: FCM Notification
    runs-on: ubuntu-latest
    steps:
      - uses: 'google-github-actions/auth@v2'
        id: google_auth
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          token_format: "access_token"
          create_credentials_file: false
      - name: Send FCM notification
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://fcm.googleapis.com/v1/projects/flippertestnotification/messages:send'
          method: 'POST'
          bearerToken: ${{ steps.google_auth.outputs.access_token }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: >
            {"message":{"notification":{"title":"Firmware Update Available","body":"New firmware version is ready to install: 0.98.2"},"condition":"'flipper_update_firmware_release' in topics"}}
